### ISSUE TITLE
Rails breaks pp?

### ISSUE THREAD

**Issue by shanna** [techspaceco/qq#3]
`pp()` isn't pretty printing rails objects. Params and models lack indentation and 80 character line wrapping.

**Comment by adamrainsby** [comment]
It works for most models but it doesn't for our User model. Pretty sure it used to.

Awesome print special case ActiveRecord::Base objects.
https://github.com/awesome-print/awesome_print/commit/3258a9bc631c95779ca45c43a2cf2b23812bc036

We could do something similar and call .attributes on instances of ActiveRecord::Base to get a hash of all the attributes

They also currently have an open issue for the params https://github.com/awesome-print/awesome_print/issues/289

**Comment by adamrainsby** [comment]
https://github.com/techspaceco/qq/pull/5/files
